<?php if ( ! defined( 'ABSPATH' ) ) {
	die( 'Direct access forbidden.' );
}

function dotdigital_filter_social_icons_icon_set( $sets ) {
	$sets['social-icons'] = array(
		'font-style-src'  => DOTDIGITAL_THEME_URI . ( '/css/fonts.css' ),
		'container-class' => '', // some fonts need special wrapper class to display properly
		'groups'          => array(
			'all' => esc_html__( 'All', 'dotdigital' ),
		),
		'icons'           => array(
			'social-icon soc-twitter'       => array( 'group' => 'all' ),
			'social-icon soc-facebook'      => array( 'group' => 'all' ),
			'social-icon soc-google'        => array( 'group' => 'all' ),
			'social-icon soc-pinterest'     => array( 'group' => 'all' ),
			'social-icon soc-foursquare'    => array( 'group' => 'all' ),
			'social-icon soc-yahoo'         => array( 'group' => 'all' ),
			'social-icon soc-skype'         => array( 'group' => 'all' ),
			'social-icon soc-yelp'          => array( 'group' => 'all' ),
			'social-icon soc-feedburner'    => array( 'group' => 'all' ),
			'social-icon soc-linkedin'      => array( 'group' => 'all' ),
			'social-icon soc-viadeo'        => array( 'group' => 'all' ),
			'social-icon soc-xing'          => array( 'group' => 'all' ),
			'social-icon soc-myspace'       => array( 'group' => 'all' ),
			'social-icon soc-soundcloud'    => array( 'group' => 'all' ),
			'social-icon soc-spotify'       => array( 'group' => 'all' ),
			'social-icon soc-grooveshark'   => array( 'group' => 'all' ),
			'social-icon soc-lastfm'        => array( 'group' => 'all' ),
			'social-icon soc-youtube'       => array( 'group' => 'all' ),
			'social-icon soc-vimeo'         => array( 'group' => 'all' ),
			'social-icon soc-dailymotion'   => array( 'group' => 'all' ),
			'social-icon soc-vine'          => array( 'group' => 'all' ),
			'social-icon soc-flickr'        => array( 'group' => 'all' ),
			'social-icon soc-500px'         => array( 'group' => 'all' ),
			'social-icon soc-instagram'     => array( 'group' => 'all' ),
			'social-icon soc-wordpress'     => array( 'group' => 'all' ),
			'social-icon soc-tumblr'        => array( 'group' => 'all' ),
			'social-icon soc-blogger'       => array( 'group' => 'all' ),
			'social-icon soc-technorati'    => array( 'group' => 'all' ),
			'social-icon soc-reddit'        => array( 'group' => 'all' ),
			'social-icon soc-dribbble'      => array( 'group' => 'all' ),
			'social-icon soc-stumbleupon'   => array( 'group' => 'all' ),
			'social-icon soc-digg'          => array( 'group' => 'all' ),
			'social-icon soc-envato'        => array( 'group' => 'all' ),
			'social-icon soc-behance'       => array( 'group' => 'all' ),
			'social-icon soc-delicious'     => array( 'group' => 'all' ),
			'social-icon soc-deviantart'    => array( 'group' => 'all' ),
			'social-icon soc-forrst'        => array( 'group' => 'all' ),
			'social-icon soc-play'          => array( 'group' => 'all' ),
			'social-icon soc-zerply'        => array( 'group' => 'all' ),
			'social-icon soc-wikipedia'     => array( 'group' => 'all' ),
			'social-icon soc-apple'         => array( 'group' => 'all' ),
			'social-icon soc-flattr'        => array( 'group' => 'all' ),
			'social-icon soc-github'        => array( 'group' => 'all' ),
			'social-icon soc-friendfeed'    => array( 'group' => 'all' ),
			'social-icon soc-newsvine'      => array( 'group' => 'all' ),
			'social-icon soc-identica'      => array( 'group' => 'all' ),
			'social-icon soc-bebo'          => array( 'group' => 'all' ),
			'social-icon soc-zynga'         => array( 'group' => 'all' ),
			'social-icon soc-steam'         => array( 'group' => 'all' ),
			'social-icon soc-xbox'          => array( 'group' => 'all' ),
			'social-icon soc-windows'       => array( 'group' => 'all' ),
			'social-icon soc-outlook'       => array( 'group' => 'all' ),
			'social-icon soc-coderwall'     => array( 'group' => 'all' ),
			'social-icon soc-tripadvisor'   => array( 'group' => 'all' ),
			'social-icon soc-appnet'        => array( 'group' => 'all' ),
			'social-icon soc-goodreads'     => array( 'group' => 'all' ),
			'social-icon soc-tripit'        => array( 'group' => 'all' ),
			'social-icon soc-lanyrd'        => array( 'group' => 'all' ),
			'social-icon soc-slideshare'    => array( 'group' => 'all' ),
			'social-icon soc-buffer'        => array( 'group' => 'all' ),
			'social-icon soc-rss'           => array( 'group' => 'all' ),
			'social-icon soc-vkontakte'     => array( 'group' => 'all' ),
			'social-icon soc-disqus'        => array( 'group' => 'all' ),
			'social-icon soc-houzz'         => array( 'group' => 'all' ),
			'social-icon soc-mail'          => array( 'group' => 'all' ),
			'social-icon soc-patreon'       => array( 'group' => 'all' ),
			'social-icon soc-paypal'        => array( 'group' => 'all' ),
			'social-icon soc-playstation'   => array( 'group' => 'all' ),
			'social-icon soc-smugmug'       => array( 'group' => 'all' ),
			'social-icon soc-swarm'         => array( 'group' => 'all' ),
			'social-icon soc-triplej'       => array( 'group' => 'all' ),
			'social-icon soc-yammer'        => array( 'group' => 'all' ),
			'social-icon soc-stackoverflow' => array( 'group' => 'all' ),
			'social-icon soc-drupal'        => array( 'group' => 'all' ),
			'social-icon soc-odnoklassniki' => array( 'group' => 'all' ),
			'social-icon soc-android'       => array( 'group' => 'all' ),
			'social-icon soc-meetup'        => array( 'group' => 'all' ),
			'social-icon soc-persona'       => array( 'group' => 'all' ),
			'social-icon soc-amazon'        => array( 'group' => 'all' ),
			'social-icon soc-ello'          => array( 'group' => 'all' ),
			'social-icon soc-mixcloud'      => array( 'group' => 'all' ),
			'social-icon soc-8tracks'       => array( 'group' => 'all' ),
			'social-icon soc-twitch'        => array( 'group' => 'all' ),
			'social-icon soc-airbnb'        => array( 'group' => 'all' ),
			'social-icon soc-pocket'        => array( 'group' => 'all' ),
		),
	);

	return $sets;
}

add_filter( 'fw_option_type_icon_sets', 'dotdigital_filter_social_icons_icon_set' );